### ISSUE TITLE
Title mangled on IOS Safari

### ISSUE THREAD

**Issue by BrassHead** [sreetamdas/sreetamdas.com#11]
FYI, The title "The perfect dark mode" comes out as "The perfect" in IOS Safari. There is a large black space where the second line of the title should be. This is the latest IOS/Safari 14.2 on an iPad air. I noticed this in dark mode, but changing to light mode had no effect.

**Comment by sreetamdas** [comment]
Sorry, could you please provide a screenshot? Thanks so much for letting me know! 😄

**Comment by BrassHead** [comment]
![image](https://user-images.githubusercontent.com/6327631/99924636-ef634b80-2cef-11eb-8833-a27fcc4ec69b.png)

**Comment by BrassHead** [comment]
It does the same thing on MacOS Big Sur Safari. It might be the font you used. After upgrading to Big Sur, I had to change fonts in VSCode because it came out black on black (the problem font was "source code pro").

**Comment by sreetamdas** [comment]
I updated Safari and looks like this is a Safari 14 issue, I'll look around for ways to fix this. Thanks again for bringing this up! 🙌

**Comment by sreetamdas** [comment]
I've deployed a temp fix: `-webkit-box-decoration-break: clone;` which shows two "rows" of text gradient like so:

<img width="936" alt="image" src="https://user-images.githubusercontent.com/11270438/99931730-a8229c80-2d7b-11eb-816d-b39255ad4240.png">
