### ISSUE TITLE
Fix `::selection` when used with text gradient

### ISSUE THREAD

**Issue by sreetamdas** [sreetamdas/sreetamdas.com#123]
Example: on [sreetamdas.com/newsletter](https://sreetamdas.com/newsletter)

`::selection`
<img width="717" alt="image" src="https://user-images.githubusercontent.com/11270438/196422223-3161149c-45cf-4cfe-a868-9b06ee207455.png">

`:hover::selection`
<img width="721" alt="image" src="https://user-images.githubusercontent.com/11270438/196422207-1059f5aa-d6e6-4714-9c46-152887964569.png">

**Comment by logicalahara** [comment]
Hey @sreetamdas would love to contribute to this. Please assign it to me.

Need some more clarity on this.

**Comment by sreetamdas** [comment]
@logicalahara sure thing, thanks! How can I help?
