### ISSUE TITLE
Add `/shiki` to create code snippet image using shiki

### ISSUE THREAD

**Issue by sreetamdas** [sreetamdas/sreetamdas.com#124]
- [ ] Use https://github.com/shikijs/shiki

**Comment by hussamkhatib** [comment]
Can I go for it.

**Comment by sreetamdas** [comment]
Hey @hussamkhatib! I've actually begun some work on this already, but have been stuck for a bit—would love to get your help on making this work though! :)

**Comment by sreetamdas** [comment]
@hussamkhatib I'm sorry but I haven't been able to work on this the past week at all. If you're still interested, I can assign this to you. Lemme know!
