### ISSUE TITLE
Your lighthouse score is misleading

### ISSUE THREAD

**Issue by bdlowery** [sreetamdas/sreetamdas.com#157]
You can’t run lighthouse in your browser. It will only take into account your internet speed and your computer speed. It’s not reflective of what google thinks of your site, or what the average user will experience when visiting.

Here is the real lighthouse score of your site: https://pagespeed.web.dev/report?url=https%3A%2F%2Fsreetamdas.com%2F

considering the site is pretty straightforward with no images, looks like there could be a lot of improvement on the pagespeed side of things :)

**Comment by sreetamdas** [comment]
Hey hey @bdlowery! Sorry for seeing this only now. 

You're right! This is on me, I haven't re-checked it in a while. But also, I've found [pagespeed.web.dev](https://pagespeed.web.dev) to be inconsistent as well—I got [75 on mobile and 99 on desktop](https://pagespeed.web.dev/analysis/https-sreetamdas-com/lgs7e5ufhs) in one test, and [85 and 89 respectively](https://pagespeed.web.dev/analysis/https-sreetamdas-com/9mjkzkop5o) on a subsequent run. 😅

I think it's best I remove the scores, until there is something more consistent in the future, or add a disclaimer explaining this inconsistency in a note right next to it. What do you think? :)

**Comment by bdlowery** [comment]
It's because vercel caches things on their cdn's. So when pagespeed visits the website vercel will cache it on that specific server. Then when you run it again it'll access that same server with the cached assets and the pagespeed will be higher.
