### ISSUE TITLE
Sentence seems to be incomplete.

### ISSUE THREAD

**Issue by lostgirljourney** [sreetamdas/sreetamdas.com#166]
https://github.com/sreetamdas/sreetamdas.com/blob/de94b9834842c8c8464b95a8769f32c5ac1cde50/src/content/credits.mdx#L14

The line above mentioned seems incomplete.

**Comment by sreetamdas** [comment]
Fixed in https://github.com/sreetamdas/sreetamdas.com/commit/fec28f6d86ab850331756d75af35c9add918640e, thanks!
