### ISSUE TITLE
Fix horizontal scroll

### ISSUE THREAD

**Issue by sudanchapagain** [sreetamdas/sreetamdas.com#186]
the `.w-screen` class on the header produces a tiny bit of extra width space that makes the page scroll-able horizontally. 

platform: Firefox 124 on Linux

**Comment by sreetamdas** [comment]
@sudanchapagain does this still occur for you?

**Comment by sudanchapagain** [comment]
Yes. I assumed it was because of my always show scrollbar setting but i created a new profile and opened the site. Same issue. 

this is on: Firefox developer version 129.0b3 Windows.

I just opened it on chrome, same issue. 

It's the issue with `.w-screen` on the parent div of header and the anchor tag for skip to main content. Does this not happen in your device? It should no?

**Comment by sudanchapagain** [comment]
Found the solution, add max-width: 100% on the div.

https://stackoverflow.com/questions/23367345/100vw-causing-horizontal-overflow-but-only-if-more-than-one
