### ISSUE TITLE
Use "@/" imports

### ISSUE THREAD

**Issue by sreetamdas** [sreetamdas/sreetamdas.com#34]
Update `tsconfig.json` and update imports everywhere needed, for example:

```diff
- import { ViewsCounter } from "components/ViewsCounter";
+ import { ViewsCounter } from "@/components/ViewsCounter";
```

Makes the import ever-so-slightly-more explicit 😄

**Comment by AnirudhPanda** [comment]
Can I take this one @sreetamdas under hacktoberfest

**Comment by vvaibhavdesai** [comment]
Hey, @AnirudhPanda  sorry to say this but already been working on it and am almost done!

**Comment by AnirudhPanda** [comment]
> Hey, @AnirudhPanda sorry to say this but already been working on it and am almost done!

I thought good practice is we should work only when assigned!

Nevermind.

**Comment by vvaibhavdesai** [comment]
Umm had a word with sreetam about this long back just forgot to update it here sorry for the inconvenience.

**Comment by sreetamdas** [comment]
@AnirudhPanda sorry the delay and misunderstanding, I've been travelling :D

I'll be waiting a bit longer to open the repo for contributions towards hacktoberfest for a couple of reasons, but please don't let that stop you from working on the issues :)

@vvaibhavdesai sorry but to clarify I'd said: "Yeah I think it's best to atleast mention that you're working on it — but I'll accept whichever PR comes in first to close the issue :)"

So in this case, @AnirudhPanda I'll gladly accept your PR as well — there's also more issues that you can work on, possibly even together :D

**Comment by sreetamdas** [comment]
Closed with https://github.com/sreetamdas/sreetamdas.com/commit/30594b9b7ab69c01d7cd8a351a5e5c606256399c
