### ISSUE TITLE
Update favicon depending on light/dark mode

### ISSUE THREAD

**Issue by sreetamdas** [sreetamdas/sreetamdas.com#37]
- The default favicon has a colour of `#9D86E9` — the primary accent colour for dark mode
- Use the corresponding SVG to add a separate favicon/modify the existing one with `#5B34DA` — the primary accent colour for light mode:

```svg
<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect width="32" height="32" rx="8" fill="#9D86E9"/>
</svg>
```

**Comment by ImSunnyDev** [comment]
Hey, 
in this new favicon should be added or just change the color of the existing one?
Thanks

**Comment by sreetamdas** [comment]
@ImSunnyDev we should have the PNG file as a fallback, and add the SVG that I've mentioned above

Hope that helps!

**Comment by imaxisXD** [comment]
@sreetamdas  if possible can you share the png file link or is it in the repo? or what is the png name
